/**
 * Routes for Deploy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { executeDeployment } from "../handlers/deploy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function deployRoutes(fastify: FastifyInstance) {
  // POST /v1/deployments/{deploymentId}/deploy (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/deployments/:deploymentId/deploy",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { deploymentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeploymentsDependenciesForRequest();
        await executeDeployment(request, reply, deps);
      });
    }
  );


}
