/**
 * Routes for Deployment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getDeployment, listDeployments, requestDeployment } from "../handlers/deployment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function deploymentRoutes(fastify: FastifyInstance) {
  // GET /v1/deployments (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/deployments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeploymentsDependenciesForRequest();
        await listDeployments(request, reply, deps);
      });
    }
  );


  // POST /v1/deployments (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/deployments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeploymentsDependenciesForRequest();
        await requestDeployment(request, reply, deps);
      });
    }
  );


  // GET /v1/deployments/{deploymentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/deployments/:deploymentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { deploymentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDeploymentsDependenciesForRequest();
        await getDeployment(request, reply, deps);
      });
    }
  );


}
