/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { decisionRoutes } from "./decision.routes.js";
export { deployRoutes } from "./deploy.routes.js";
export { deploymentRoutes } from "./deployment.routes.js";
export { retireRoutes } from "./retire.routes.js";
export { rollbackRoutes } from "./rollback.routes.js";
