/**
 * Routes for Export
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidencepacks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { exportEvidencePack } from "../handlers/export.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function exportRoutes(fastify: FastifyInstance) {
  // POST /v1/evidence-packs/{evidencePackId}/export (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/evidence-packs/:evidencePackId/export",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { evidencePackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getEvidencepacksDependenciesForRequest();
        await exportEvidencePack(request, reply, deps);
      });
    }
  );


}
