/**
 * CreateModelEvidencePack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidencepacks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createModelEvidencePack } from "@aetherlab/api-server/domains/evidencepacks/handlers";
import type { EvidencepacksDDDDependencies } from "@aetherlab/api-server/domains/evidencepacks";
import { createEvidencePack as createEvidencePackEntity } from "@aetherlab/factories/evidencepacks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aetherlab/tests/shared";
import { EVIDENCEPACKS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateModelEvidencePack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvidencepacksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvidencepacksDDDDependencies>(
      EVIDENCEPACKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createEvidencePackEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateModelEvidencePack, "execute").mockResolvedValue(useCaseResult);

    await createModelEvidencePack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateModelEvidencePack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
