/**
 * Handlers for Decision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvaluationsDomainModule } from "../dependencies/evaluations-ddd.dependencies.js";
import type { DecideEvaluationInput } from "@aetherlab/services/evaluations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/evaluations/{evaluationId}/decision
 * Operation: decideEvaluation
 */
export async function decideEvaluation(
  request: FastifyRequest<{ Params: { evaluationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvaluationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    evaluationId: request.params.evaluationId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decisions.get.execute(input);
  return reply.code(200).send(result);
}


