/**
 * FrameRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FrameRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FrameRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FrameRepository,
} from "@aetherlab/services/projects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FrameRepositoryDdb } from "./frame-repository.ddb.js";

/**
 * FrameRepositoryAdapter
 *
 * Implements FrameRepository port for infrastructure layer.
 */
export class FrameRepositoryAdapter implements FrameRepository {
  private readonly ddb: FrameRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FrameRepositoryDdb(this.dynamoClient);
  }

  async submitProjectProblemFrame(input: Parameters<FrameRepository['submitProjectProblemFrame']>[0]): Promise<Awaited<ReturnType<FrameRepository['submitProjectProblemFrame']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitProjectProblemFrame(input);
  }
}
