/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./frame-repository.ddb.js";
export * from "./project-repository.ddb.js";
export * from "./risk-class-gate-repository.ddb.js";
export * from "./scale-quotum-repository.ddb.js";
export * from "./frame-repository.adapter.js";
export * from "./project-repository.adapter.js";
export * from "./risk-class-gate-repository.adapter.js";
export * from "./scale-quotum-repository.adapter.js";
