/**
 * ProjectRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProjectRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProjectRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProjectRepository,
} from "@aetherlab/services/projects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProjectRepositoryDdb } from "./project-repository.ddb.js";

/**
 * ProjectRepositoryAdapter
 *
 * Implements ProjectRepository port for infrastructure layer.
 */
export class ProjectRepositoryAdapter implements ProjectRepository {
  private readonly ddb: ProjectRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProjectRepositoryDdb(this.dynamoClient);
  }

  async listProjects(input: Parameters<ProjectRepository['listProjects']>[0]): Promise<Awaited<ReturnType<ProjectRepository['listProjects']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listProjects(input);
  }

  async createProject(input: Parameters<ProjectRepository['createProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['createProject']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createProject(input);
  }

  async getProject(input: Parameters<ProjectRepository['getProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['getProject']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getProject(input);
  }
}
