/**
 * ProjectRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProjectRepositoryDdb
 *
 * DDD: Infrastructure adapter for Project repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { ProjectRepository } from "@aetherlab/services/projects";
import { factoryOps } from "../_shared/factory-ops.js";

export class ProjectRepositoryDdb implements ProjectRepository {
  constructor(private readonly dynamoClient: any) {}

  async listProjects(input: Parameters<ProjectRepository['listProjects']>[0]): Promise<Awaited<ReturnType<ProjectRepository['listProjects']>>>  {
    return factoryOps.listProjects(input) as any;
  }

  async createProject(input: Parameters<ProjectRepository['createProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['createProject']>>>  {
    return factoryOps.createProject(input) as any;
  }

  async getProject(input: Parameters<ProjectRepository['getProject']>[0]): Promise<Awaited<ReturnType<ProjectRepository['getProject']>>>  {
    return factoryOps.getProject(input) as any;
  }
}
