/**
 * RiskClassGateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskClassGateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RiskClassGateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RiskClassGateRepository,
} from "@aetherlab/services/projects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RiskClassGateRepositoryDdb } from "./risk-class-gate-repository.ddb.js";

/**
 * RiskClassGateRepositoryAdapter
 *
 * Implements RiskClassGateRepository port for infrastructure layer.
 */
export class RiskClassGateRepositoryAdapter implements RiskClassGateRepository {
  private readonly ddb: RiskClassGateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RiskClassGateRepositoryDdb(this.dynamoClient);
  }

  async getRiskClassGateMatrix(input: Parameters<RiskClassGateRepository['getRiskClassGateMatrix']>[0]): Promise<Awaited<ReturnType<RiskClassGateRepository['getRiskClassGateMatrix']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRiskClassGateMatrix(input);
  }
}
