/**
 * ScaleQuotumRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ScaleQuotumRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ScaleQuotumRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ScaleQuotumRepository,
} from "@aetherlab/services/projects";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ScaleQuotumRepositoryDdb } from "./scale-quotum-repository.ddb.js";

/**
 * ScaleQuotumRepositoryAdapter
 *
 * Implements ScaleQuotumRepository port for infrastructure layer.
 */
export class ScaleQuotumRepositoryAdapter implements ScaleQuotumRepository {
  private readonly ddb: ScaleQuotumRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ScaleQuotumRepositoryDdb(this.dynamoClient);
  }

  async decideProjectScaleQuota(input: Parameters<ScaleQuotumRepository['decideProjectScaleQuota']>[0]): Promise<Awaited<ReturnType<ScaleQuotumRepository['decideProjectScaleQuota']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.decideProjectScaleQuota(input);
  }
}
