/**
 * ExecuteListMonitors - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListMonitors Use Case
 *
 * DDD: Application use case for list Monitor.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListMonitorsInput, ListMonitorsOutput } from "../dto/monitor.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { MonitorRepository } from "../ports";

export class ExecuteListMonitors {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly monitor: MonitorRepository
  ) {}

  async execute(input: ListMonitorsInput): Promise<ListMonitorsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.monitor.listMonitors({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListMonitorsOutput;
  }
}
