/**
 * ExecuteGetMonitor - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetMonitor Use Case
 *
 * DDD: Application use case for get Monitor.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetMonitorInput, GetMonitorOutput } from "../dto/monitor.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { MonitorRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetMonitor {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly monitor: MonitorRepository
  ) {}

  async execute(input: GetMonitorInput): Promise<GetMonitorOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.monId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).monitorId) {
      throw new ValidationError("monitorId is required");
    }
    const monitorId = (input as any).monitorId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.monitor.getMonitor({ monitorId: monitorId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${monitorId}`);
    }

    return entity as GetMonitorOutput;
  }
}
