/**
 * DarkFind DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DarkFind DTOs
 *
 * DDD: Application DTOs for DarkFind use cases.
 */

import type { ForceRegisterDarkFindRequestInput } from "@aetherlab/core/models/types";

export type ForceRegisterDarkFindInput = ForceRegisterDarkFindRequestInput;

export type ForceRegisterDarkFindOutput = {};
