/**
 * VModel DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModel DTOs
 *
 * DDD: Application DTOs for VModel use cases.
 */

import type { CreateModelRequestInput, GetModelParams, ListModelsParams } from "@aetherlab/core/models/types";

export type ListModelsInput = ListModelsParams;

export type CreateModelInput = CreateModelRequestInput;

export type GetModelInput = GetModelParams;

export type ListModelsOutput = {};

export type CreateModelOutput = {};

export type GetModelOutput = {};
