/**
 * FrameRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FrameRepository Port
 *
 * DDD: Application port for framerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SubmitProjectProblemFrameInput, SubmitProjectProblemFrameOutput } from "../dto/frame.dto";
export interface FrameRepository {
  submitProjectProblemFrame(input: SubmitProjectProblemFrameInput): Promise<SubmitProjectProblemFrameOutput>;
}

export type { SubmitProjectProblemFrameInput, SubmitProjectProblemFrameOutput } from "../dto/frame.dto";
