/**
 * ProjectRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProjectRepository Port
 *
 * DDD: Application port for projectrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateProjectInput, CreateProjectOutput, GetProjectInput, GetProjectOutput, ListProjectsInput, ListProjectsOutput } from "../dto/project.dto";
export interface ProjectRepository {
  listProjects(input: ListProjectsInput): Promise<ListProjectsOutput>;
  createProject(input: CreateProjectInput): Promise<CreateProjectOutput>;
  getProject(input: GetProjectInput): Promise<GetProjectOutput>;
}

export type { CreateProjectInput, CreateProjectOutput, GetProjectInput, GetProjectOutput, ListProjectsInput, ListProjectsOutput } from "../dto/project.dto";
