/**
 * RiskClassGateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RiskClassGateRepository Port
 *
 * DDD: Application port for riskclassgaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetRiskClassGateMatrixInput, GetRiskClassGateMatrixOutput } from "../dto/risk-class-gate.dto";
export interface RiskClassGateRepository {
  getRiskClassGateMatrix(input: GetRiskClassGateMatrixInput): Promise<GetRiskClassGateMatrixOutput>;
}

export type { GetRiskClassGateMatrixInput, GetRiskClassGateMatrixOutput } from "../dto/risk-class-gate.dto";
