/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the trainingjobs domain.
 * Use these factories in tests to create test data.
 */

export { createCreateStopRequest } from "./stop/dto/create-stop.dto.factory.js";
export { createTrainingJob } from "./training-job/entity/training-job.entity.factory.js";
