/**
 * Handlers for Export
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidencepacks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EvidencepacksDomainModule } from "../dependencies/evidencepacks-ddd.dependencies.js";
import type { ExportEvidencePackInput } from "@aetherlab/services/evidencepacks";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/evidence-packs/{evidencePackId}/export
 * Operation: exportEvidencePack
 */
export async function exportEvidencePack(
  request: FastifyRequest<{ Params: { evidencePackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EvidencepacksDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    evidencePackId: request.params.evidencePackId,
  };
  const result = await deps.useCases.exports.list.execute(input);
  return reply.code(200).send(result);
}


