/**
 * ExportEvidencePack handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidencepacks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { exportEvidencePack } from "@aetherlab/api-server/domains/evidencepacks/handlers";
import type { EvidencepacksDDDDependencies } from "@aetherlab/api-server/domains/evidencepacks";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aetherlab/tests/shared";
import { EVIDENCEPACKS_USE_CASES } from "../__factories__/use-cases.js";

describe("ExportEvidencePack", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EvidencepacksDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EvidencepacksDDDDependencies>(
      EVIDENCEPACKS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      { id: 'mock-1', orgId } as any,
      { id: 'mock-2', orgId } as any,
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeExportEvidencePack, "execute").mockResolvedValue(useCaseResult);

    await exportEvidencePack(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeExportEvidencePack.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
