/**
 * DecisionRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionRepositoryDdb
 *
 * DDD: Infrastructure adapter for Decision repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { DecisionRepository } from "@aetherlab/services/evaluations";
import { factoryOps } from "../_shared/factory-ops.js";

export class DecisionRepositoryDdb implements DecisionRepository {
  constructor(private readonly dynamoClient: any) {}

  async decideEvaluation(input: Parameters<DecisionRepository['decideEvaluation']>[0]): Promise<Awaited<ReturnType<DecisionRepository['decideEvaluation']>>>  {
    return factoryOps.decideEvaluation(input) as any;
  }
}
