/**
 * ExecuteGetTrainingJob - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetTrainingJob Use Case
 *
 * DDD: Application use case for get TrainingJob.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetTrainingJobInput, GetTrainingJobOutput } from "../dto/training-job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { TrainingJobRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetTrainingJob {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly trainingJob: TrainingJobRepository
  ) {}

  async execute(input: GetTrainingJobInput): Promise<GetTrainingJobOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trnId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).trainingJobId) {
      throw new ValidationError("trainingJobId is required");
    }
    const trainingjobId = (input as any).trainingJobId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.trainingJob.getTrainingJob({ trainingJobId: trainingjobId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${trainingjobId}`);
    }

    return entity as GetTrainingJobOutput;
  }
}
