/**
 * ExecuteListTrainingJobs - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTrainingJobs Use Case
 *
 * DDD: Application use case for list TrainingJob.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTrainingJobsInput, ListTrainingJobsOutput } from "../dto/training-job.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { TrainingJobRepository } from "../ports";

export class ExecuteListTrainingJobs {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly trainingJob: TrainingJobRepository
  ) {}

  async execute(input: ListTrainingJobsInput): Promise<ListTrainingJobsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trnId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.trainingJob.listTrainingJobs({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTrainingJobsOutput;
  }
}
