/**
 * Project DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Project DTOs
 *
 * DDD: Application DTOs for Project use cases.
 */

import type { CreateProjectRequestInput, GetProjectParams, ListProjectsParams } from "@aetherlab/core/projects/types";

export type ListProjectsInput = ListProjectsParams;

export type CreateProjectInput = CreateProjectRequestInput;

export type GetProjectInput = GetProjectParams;

export type ListProjectsOutput = {};

export type CreateProjectOutput = {};

export type GetProjectOutput = {};
