/**
 * Repository interface for TrainingJob
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  TrainingJobEntity
} from "../models/training-job.entity.js";
import type {
  ListTrainingJobsParams,
  TrainingJob
} from "../types/index.js";
/**
 * TrainingJobRepository Interface
 */
export interface TrainingJobRepository extends CreateReadRepository<TrainingJobEntity, TrainingJob, string, ListTrainingJobsParams> {

}
