/**
 * Monitor DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Monitor DTOs
 *
 * DDD: Application DTOs for Monitor use cases.
 */

import type { CreateMonitorRequestInput, GetMonitorParams, ListMonitorsParams } from "@aetherlab/core/monitors/types";

export type ListMonitorsInput = ListMonitorsParams;

export type CreateMonitorInput = CreateMonitorRequestInput;

export type GetMonitorInput = GetMonitorParams;

export type ListMonitorsOutput = {};

export type CreateMonitorOutput = {};

export type GetMonitorOutput = {};
