/**
 * Handlers for Monitor
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { MonitorsDomainModule } from "../dependencies/monitors-ddd.dependencies.js";
import type { CreateMonitorInput, GetMonitorInput, ListMonitorsInput } from "@aetherlab/services/monitors";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/monitors
 * Operation: listMonitors
 */
export async function listMonitors(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], modelId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: MonitorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.monitors.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/monitors
 * Operation: createMonitor
 */
export async function createMonitor(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: MonitorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.monitors.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/monitors/{monitorId}
 * Operation: getMonitor
 */
export async function getMonitor(
  request: FastifyRequest<{ Params: { monitorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: MonitorsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    monitorId: request.params.monitorId,
  };
  const result = await deps.useCases.monitors.get.execute(input);
  return reply.code(200).send(result);
}


