/**
 * GetDeployment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetDeploymentParams } from "@aetherlab/core/deployments";

export function createGetDeploymentRequest(overrides: Partial<GetDeploymentParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
