/**
 * Routes for BaseWeight
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { registerTrainingJobBaseWeight } from "../handlers/base-weight.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function baseWeightRoutes(fastify: FastifyInstance) {
  // POST /v1/training-jobs/{trainingJobId}/base-weight (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/training-jobs/:trainingJobId/base-weight",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { trainingJobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTrainingjobsDependenciesForRequest();
        await registerTrainingJobBaseWeight(request, reply, deps);
      });
    }
  );


}
