/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { spendRoutes } from "./spend.routes.js";
export { baseWeightRoutes } from "./base-weight.routes.js";
export { stopRoutes } from "./stop.routes.js";
export { trainingJobRoutes } from "./training-job.routes.js";
