/**
 * Routes for TrainingJob
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createTrainingJob, getTrainingJob, listTrainingJobs } from "../handlers/training-job.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function trainingJobRoutes(fastify: FastifyInstance) {
  // POST /v1/training-jobs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/training-jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTrainingjobsDependenciesForRequest();
        await createTrainingJob(request, reply, deps);
      });
    }
  );


  // GET /v1/training-jobs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/training-jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTrainingjobsDependenciesForRequest();
        await listTrainingJobs(request, reply, deps);
      });
    }
  );


  // GET /v1/training-jobs/{trainingJobId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/training-jobs/:trainingJobId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { trainingJobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTrainingjobsDependenciesForRequest();
        await getTrainingJob(request, reply, deps);
      });
    }
  );


}
