/**
 * RiskClassGate Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { RiskClassGateEntity } from "@aetherlab/core/projects/models/index.js";
import { projectsSchemas } from "@aetherlab/core/projects";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prj";

export function createRiskClassGate(overrides: Partial<RiskClassGateEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    dualControl: overrides.dualControl ?? faker.datatype.boolean(),
    monitorsRequired: overrides.monitorsRequired ?? faker.datatype.boolean(),
    requiredArtefacts: overrides.requiredArtefacts ?? [],
    riskClass: overrides.riskClass ?? "low",
    ...overrides,
  };

  return projectsSchemas.RiskClassGate.parse(raw);
}

export function riskClassGateBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createRiskClassGate(overrides));
}
