/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: evidencepacks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @aetherlab/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@aetherlab/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@aetherlab/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@aetherlab/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@aetherlab/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@aetherlab/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _datasets from "./datasets/index.js";
import * as _deployments from "./deployments/index.js";
import * as _evaluations from "./evaluations/index.js";
import * as _evidencepacks from "./evidencepacks/index.js";
import * as _identity from "./identity/index.js";
import * as _models from "./models/index.js";
import * as _monitors from "./monitors/index.js";
import * as _projects from "./projects/index.js";
import * as _trainingjobs from "./trainingjobs/index.js";

// Export as namespaces
export const _shared = __shared;
export const datasets = _datasets;
export const deployments = _deployments;
export const evaluations = _evaluations;
export const evidencepacks = _evidencepacks;
export const identity = _identity;
export const models = _models;
export const monitors = _monitors;
export const projects = _projects;
export const trainingjobs = _trainingjobs;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@aetherlab/core"; activity.types.*
//   - Direct exports: import * from "@aetherlab/core/activity/types/index.js"
//   - Direct exports: import * from "@aetherlab/core/activity/repositories/index.js"
//   - Direct exports: import * from "@aetherlab/core/activity/models/index.js"
//   - Direct exports: import * from "@aetherlab/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Datasets Service
export { schemas as DatasetsSchemas } from "./datasets/schemas/datasets.schemas.js";

// Deployments Service
export { schemas as DeploymentsSchemas } from "./deployments/schemas/deployments.schemas.js";

// Evaluations Service
export { schemas as EvaluationsSchemas } from "./evaluations/schemas/evaluations.schemas.js";

// Evidencepacks Service
export { schemas as EvidencepacksSchemas } from "./evidencepacks/schemas/evidencepacks.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Models Service
export { schemas as ModelsSchemas } from "./models/schemas/models.schemas.js";

// Monitors Service
export { schemas as MonitorsSchemas } from "./monitors/schemas/monitors.schemas.js";

// Projects Service
export { schemas as ProjectsSchemas } from "./projects/schemas/projects.schemas.js";

// Trainingjobs Service
export { schemas as TrainingjobsSchemas } from "./trainingjobs/schemas/trainingjobs.schemas.js";

