/**
 * DarkFindRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DarkFindRepositoryDdb
 *
 * DDD: Infrastructure adapter for DarkFind repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { DarkFindRepository } from "@aetherlab/services/models";
import { factoryOps } from "../_shared/factory-ops.js";

export class DarkFindRepositoryDdb implements DarkFindRepository {
  constructor(private readonly dynamoClient: any) {}

  async forceRegisterDarkFind(input: Parameters<DarkFindRepository['forceRegisterDarkFind']>[0]): Promise<Awaited<ReturnType<DarkFindRepository['forceRegisterDarkFind']>>>  {
    return factoryOps.forceRegisterDarkFind(input) as any;
  }
}
