/**
 * DarkFindRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DarkFindRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DarkFindRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DarkFindRepository,
} from "@aetherlab/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DarkFindRepositoryDdb } from "./dark-find-repository.ddb.js";

/**
 * DarkFindRepositoryAdapter
 *
 * Implements DarkFindRepository port for infrastructure layer.
 */
export class DarkFindRepositoryAdapter implements DarkFindRepository {
  private readonly ddb: DarkFindRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DarkFindRepositoryDdb(this.dynamoClient);
  }

  async forceRegisterDarkFind(input: Parameters<DarkFindRepository['forceRegisterDarkFind']>[0]): Promise<Awaited<ReturnType<DarkFindRepository['forceRegisterDarkFind']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.forceRegisterDarkFind(input);
  }
}
