/**
 * VModelRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModelRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VModelRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VModelRepository,
} from "@aetherlab/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VModelRepositoryDdb } from "./vmodel-repository.ddb.js";

/**
 * VModelRepositoryAdapter
 *
 * Implements VModelRepository port for infrastructure layer.
 */
export class VModelRepositoryAdapter implements VModelRepository {
  private readonly ddb: VModelRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VModelRepositoryDdb(this.dynamoClient);
  }

  async listModels(input: Parameters<VModelRepository['listModels']>[0]): Promise<Awaited<ReturnType<VModelRepository['listModels']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listModels(input);
  }

  async createModel(input: Parameters<VModelRepository['createModel']>[0]): Promise<Awaited<ReturnType<VModelRepository['createModel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createModel(input);
  }

  async getModel(input: Parameters<VModelRepository['getModel']>[0]): Promise<Awaited<ReturnType<VModelRepository['getModel']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getModel(input);
  }
}
