/**
 * VModelRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModelRepositoryDdb
 *
 * DDD: Infrastructure adapter for VModel repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { VModelRepository } from "@aetherlab/services/models";
import { factoryOps } from "../_shared/factory-ops.js";

export class VModelRepositoryDdb implements VModelRepository {
  constructor(private readonly dynamoClient: any) {}

  async listModels(input: Parameters<VModelRepository['listModels']>[0]): Promise<Awaited<ReturnType<VModelRepository['listModels']>>>  {
    return factoryOps.listModels(input) as any;
  }

  async createModel(input: Parameters<VModelRepository['createModel']>[0]): Promise<Awaited<ReturnType<VModelRepository['createModel']>>>  {
    return factoryOps.createModel(input) as any;
  }

  async getModel(input: Parameters<VModelRepository['getModel']>[0]): Promise<Awaited<ReturnType<VModelRepository['getModel']>>>  {
    return factoryOps.getModel(input) as any;
  }
}
