/**
 * CreateTrainingJob handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createTrainingJob } from "@aetherlab/api-server/domains/trainingjobs/handlers";
import type { TrainingjobsDDDDependencies } from "@aetherlab/api-server/domains/trainingjobs";
import { createTrainingJob as createTrainingJobEntity } from "@aetherlab/factories/trainingjobs";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aetherlab/tests/shared";
import { TRAININGJOBS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateTrainingJob", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TrainingjobsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TrainingjobsDDDDependencies>(
      TRAININGJOBS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createTrainingJobEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateTrainingJob, "execute").mockResolvedValue(useCaseResult);

    await createTrainingJob(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateTrainingJob.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
