/**
 * Routes for Monitor
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createMonitor, getMonitor, listMonitors } from "../handlers/monitor.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function monitorRoutes(fastify: FastifyInstance) {
  // POST /v1/monitors (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/monitors",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonitorsDependenciesForRequest();
        await createMonitor(request, reply, deps);
      });
    }
  );


  // GET /v1/monitors (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/monitors",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonitorsDependenciesForRequest();
        await listMonitors(request, reply, deps);
      });
    }
  );


  // GET /v1/monitors/{monitorId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/monitors/:monitorId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { monitorId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMonitorsDependenciesForRequest();
        await getMonitor(request, reply, deps);
      });
    }
  );


}
