/**
 * ListMonitors handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listMonitors } from "@aetherlab/api-server/domains/monitors/handlers";
import type { MonitorsDDDDependencies } from "@aetherlab/api-server/domains/monitors";
import { createMonitor as createMonitorEntity } from "@aetherlab/factories/monitors";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aetherlab/tests/shared";
import { MONITORS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListMonitors", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MonitorsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MonitorsDDDDependencies>(
      MONITORS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createMonitorEntity({ orgId }),
      createMonitorEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListMonitors, "execute").mockResolvedValue(useCaseResult);

    await listMonitors(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListMonitors.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
