/**
 * ExecuteForceRegisterDarkFind - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteForceRegisterDarkFind Use Case
 *
 * DDD: Application use case for get DarkFind.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ForceRegisterDarkFindInput, ForceRegisterDarkFindOutput } from "../dto/dark-find.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { DarkFindRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteForceRegisterDarkFind {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly darkFind: DarkFindRepository
  ) {}

  async execute(input: ForceRegisterDarkFindInput): Promise<ForceRegisterDarkFindOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec: cloudLocus, endpointName, name, notes, projectId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).projectId) {
      throw new ValidationError("projectId is required");
    }
    const projectId = (input as any).projectId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.darkFind.forceRegisterDarkFind({ projectId: projectId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${projectId}`);
    }

    return entity as ForceRegisterDarkFindOutput;
  }
}
