/**
 * ExecuteListModels - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListModels Use Case
 *
 * DDD: Application use case for list VModel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListModelsInput, ListModelsOutput } from "../dto/vmodel.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { VModelRepository } from "../ports";

export class ExecuteListModels {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly vModel: VModelRepository
  ) {}

  async execute(input: ListModelsInput): Promise<ListModelsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.vModel.listModels({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListModelsOutput;
  }
}
