/**
 * Handlers for BaseWeight
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TrainingjobsDomainModule } from "../dependencies/trainingjobs-ddd.dependencies.js";
import type { RegisterTrainingJobBaseWeightInput } from "@aetherlab/services/trainingjobs";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/training-jobs/{trainingJobId}/base-weight
 * Operation: registerTrainingJobBaseWeight
 */
export async function registerTrainingJobBaseWeight(
  request: FastifyRequest<{ Params: { trainingJobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TrainingjobsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    trainingJobId: request.params.trainingJobId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.baseWeights.create.execute(input);
  return reply.code(200).send(result);
}


