/**
 * Repository interface for Monitor
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  MonitorEntity
} from "../models/monitor.entity.js";
import type {
  ListMonitorsParams,
  Monitor
} from "../types/index.js";
/**
 * MonitorRepository Interface
 */
export interface MonitorRepository extends CreateReadRepository<MonitorEntity, Monitor, string, ListMonitorsParams> {

}
