/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Trainingjobs Domain Use Cases
 * 
 * List of all use case names for the trainingjobs domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const TRAININGJOBS_USE_CASES = [
  "executeCreateTrainingJob",
  "executeGetTrainingJob",
  "executeListCloudSpend",
  "executeListTrainingJobs",
  "executeRegisterTrainingJobBaseWeight",
  "executeStopTrainingJob"
] as const;
