/**
 * GetMonitor DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetMonitorParams } from "@aetherlab/core/monitors";

export function createGetMonitorRequest(overrides: Partial<GetMonitorParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
