/**
 * Evaluations DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Evaluations Domain Module - Composition root
 *
 * DDD: Composition root for evaluations domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DecisionRepositoryAdapter,
  EvaluationRepositoryAdapter,
} from "@aetherlab/adapters/evaluations";
import { getIdGeneratorService } from "@aetherlab/adapters";
import type { AdapterDynamoDBClient } from "@aetherlab/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateEvaluation,
  ExecuteDecideEvaluation,
  ExecuteGetEvaluation,
  ExecuteListEvaluations,
} from "@aetherlab/services/evaluations/usecases";
// Ports (interfaces)
import type {
  DecisionRepository,
  EvaluationRepository,
} from "@aetherlab/services/evaluations/ports";

export interface EvaluationsDomainModule {
  repos: {
    decisions: DecisionRepository;
    evaluations: EvaluationRepository;
  };
  useCases: {
    decisions: {
      get: ExecuteDecideEvaluation;
    };
    evaluations: {
      create: ExecuteCreateEvaluation;
      get: ExecuteGetEvaluation;
      list: ExecuteListEvaluations;
    };
  };
}

export function buildEvaluationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EvaluationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      decisions?: DecisionRepository;
      evaluations?: EvaluationRepository;
    } = {};

    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    obj.evaluations = new EvaluationRepositoryAdapter(dynamoClient);
    return {
      decisions: obj.decisions!,
      evaluations: obj.evaluations!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    decisions: {
      get: new ExecuteDecideEvaluation(executionContext, idGenerator, repos.decisions),
    },
    evaluations: {
      create: new ExecuteCreateEvaluation(executionContext, idGenerator, repos.evaluations),
      get: new ExecuteGetEvaluation(executionContext, idGenerator, repos.evaluations),
      list: new ExecuteListEvaluations(executionContext, idGenerator, repos.evaluations),
    },
  };
  return { repos, useCases: useCases as EvaluationsDomainModule["useCases"] };
}
