/**
 * BaseWeightRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BaseWeightRepositoryDdb
 *
 * DDD: Infrastructure adapter for BaseWeight repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { BaseWeightRepository } from "@aetherlab/services/trainingjobs";
import { factoryOps } from "../_shared/factory-ops.js";

export class BaseWeightRepositoryDdb implements BaseWeightRepository {
  constructor(private readonly dynamoClient: any) {}

  async registerTrainingJobBaseWeight(input: Parameters<BaseWeightRepository['registerTrainingJobBaseWeight']>[0]): Promise<Awaited<ReturnType<BaseWeightRepository['registerTrainingJobBaseWeight']>>>  {
    return factoryOps.registerTrainingJobBaseWeight(input) as any;
  }
}
