/**
 * BaseWeightRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BaseWeightRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BaseWeightRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BaseWeightRepository,
} from "@aetherlab/services/trainingjobs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BaseWeightRepositoryDdb } from "./base-weight-repository.ddb.js";

/**
 * BaseWeightRepositoryAdapter
 *
 * Implements BaseWeightRepository port for infrastructure layer.
 */
export class BaseWeightRepositoryAdapter implements BaseWeightRepository {
  private readonly ddb: BaseWeightRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BaseWeightRepositoryDdb(this.dynamoClient);
  }

  async registerTrainingJobBaseWeight(input: Parameters<BaseWeightRepository['registerTrainingJobBaseWeight']>[0]): Promise<Awaited<ReturnType<BaseWeightRepository['registerTrainingJobBaseWeight']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerTrainingJobBaseWeight(input);
  }
}
