/**
 * StopRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StopRepositoryDdb
 *
 * DDD: Infrastructure adapter for Stop repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { StopRepository } from "@aetherlab/services/trainingjobs";
import { factoryOps } from "../_shared/factory-ops.js";

export class StopRepositoryDdb implements StopRepository {
  constructor(private readonly dynamoClient: any) {}

  async stopTrainingJob(input: Parameters<StopRepository['stopTrainingJob']>[0]): Promise<Awaited<ReturnType<StopRepository['stopTrainingJob']>>>  {
    return factoryOps.stopTrainingJob(input) as any;
  }
}
