/**
 * TrainingJobRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrainingJobRepositoryDdb
 *
 * DDD: Infrastructure adapter for TrainingJob repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { TrainingJobRepository } from "@aetherlab/services/trainingjobs";
import { factoryOps } from "../_shared/factory-ops.js";

export class TrainingJobRepositoryDdb implements TrainingJobRepository {
  constructor(private readonly dynamoClient: any) {}

  async listTrainingJobs(input: Parameters<TrainingJobRepository['listTrainingJobs']>[0]): Promise<Awaited<ReturnType<TrainingJobRepository['listTrainingJobs']>>>  {
    return factoryOps.listTrainingJobs(input) as any;
  }

  async createTrainingJob(input: Parameters<TrainingJobRepository['createTrainingJob']>[0]): Promise<Awaited<ReturnType<TrainingJobRepository['createTrainingJob']>>>  {
    return factoryOps.createTrainingJob(input) as any;
  }

  async getTrainingJob(input: Parameters<TrainingJobRepository['getTrainingJob']>[0]): Promise<Awaited<ReturnType<TrainingJobRepository['getTrainingJob']>>>  {
    return factoryOps.getTrainingJob(input) as any;
  }
}
