/**
 * Decision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decision DTOs
 *
 * DDD: Application DTOs for Decision use cases.
 */

import type { DecideDeploymentParams, DecideDeploymentRequestInput } from "@aetherlab/core/deployments/types";

export type DecideDeploymentInput = DecideDeploymentParams & DecideDeploymentRequestInput;

export type DecideDeploymentOutput = {};
