/**
 * Deploy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Deploy DTOs
 *
 * DDD: Application DTOs for Deploy use cases.
 */

import type { ExecuteDeploymentParams } from "@aetherlab/core/deployments/types";

export type ExecuteDeploymentInput = ExecuteDeploymentParams;

export type ExecuteDeploymentOutput = {};
