/**
 * Deployment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Deployment DTOs
 *
 * DDD: Application DTOs for Deployment use cases.
 */

import type { GetDeploymentParams, ListDeploymentsParams, RequestDeploymentRequestInput } from "@aetherlab/core/deployments/types";

export type ListDeploymentsInput = ListDeploymentsParams;

export type RequestDeploymentInput = RequestDeploymentRequestInput;

export type GetDeploymentInput = GetDeploymentParams;

export type ListDeploymentsOutput = {};

export type RequestDeploymentOutput = {};

export type GetDeploymentOutput = {};
