/**
 * Rollback DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Rollback DTOs
 *
 * DDD: Application DTOs for Rollback use cases.
 */

import type { RollbackDeploymentParams, RollbackDeploymentRequestInput } from "@aetherlab/core/deployments/types";

export type RollbackDeploymentInput = RollbackDeploymentParams & RollbackDeploymentRequestInput;

export type RollbackDeploymentOutput = {};
