/**
 * MonitorRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MonitorRepository Port
 *
 * DDD: Application port for monitorrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateMonitorInput, CreateMonitorOutput, GetMonitorInput, GetMonitorOutput, ListMonitorsInput, ListMonitorsOutput } from "../dto/monitor.dto";
export interface MonitorRepository {
  listMonitors(input: ListMonitorsInput): Promise<ListMonitorsOutput>;
  createMonitor(input: CreateMonitorInput): Promise<CreateMonitorOutput>;
  getMonitor(input: GetMonitorInput): Promise<GetMonitorOutput>;
}

export type { CreateMonitorInput, CreateMonitorOutput, GetMonitorInput, GetMonitorOutput, ListMonitorsInput, ListMonitorsOutput } from "../dto/monitor.dto";
