/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the deployments domain.
 * Use these factories in tests to create test data.
 */

export { createCreateDeployRequest } from "./deploy/dto/create-deploy.dto.factory.js";
export { createCreateRetireRequest } from "./retire/dto/create-retire.dto.factory.js";
