/**
 * VModelRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VModelRepository Port
 *
 * DDD: Application port for vmodelrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateModelInput, CreateModelOutput, GetModelInput, GetModelOutput, ListModelsInput, ListModelsOutput } from "../dto/vmodel.dto";
export interface VModelRepository {
  listModels(input: ListModelsInput): Promise<ListModelsOutput>;
  createModel(input: CreateModelInput): Promise<CreateModelOutput>;
  getModel(input: GetModelInput): Promise<GetModelOutput>;
}

export type { CreateModelInput, CreateModelOutput, GetModelInput, GetModelOutput, ListModelsInput, ListModelsOutput } from "../dto/vmodel.dto";
