/**
 * BaseWeight DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BaseWeight DTOs
 *
 * DDD: Application DTOs for BaseWeight use cases.
 */

import type { RegisterTrainingJobBaseWeightParams, RegisterTrainingJobBaseWeightRequestInput } from "@aetherlab/core/trainingjobs/types";

export type RegisterTrainingJobBaseWeightInput = RegisterTrainingJobBaseWeightParams & RegisterTrainingJobBaseWeightRequestInput;

export type RegisterTrainingJobBaseWeightOutput = {};
