/**
 * Stop DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Stop DTOs
 *
 * DDD: Application DTOs for Stop use cases.
 */

import type { StopTrainingJobParams } from "@aetherlab/core/trainingjobs/types";

export type StopTrainingJobInput = StopTrainingJobParams;

export type StopTrainingJobOutput = {};
