/**
 * RiskClassGate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/projects.openapi.types.js";
import { schemas } from "../schemas/projects.schemas.js";

/**
 * Entity: RiskClassGateEntity
 * Description: Represents the RiskClassGate domain model.
 * Source: schemas.RiskClassGate
 * Type: Domain Entity (API)
 */
export const RiskClassGateEntitySchema = schemas.RiskClassGate;
export type RiskClassGateEntity = components["schemas"]["RiskClassGate"];
