/**
 * CreateStop DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { StopTrainingJobParams } from "@aetherlab/core/trainingjobs";

export function createCreateStopRequest(overrides: Partial<StopTrainingJobParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
