/**
 * Decision DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decision DTOs
 *
 * DDD: Application DTOs for Decision use cases.
 */

import type { DecideEvaluationParams, DecideEvaluationRequestInput } from "@aetherlab/core/evaluations/types";

export type DecideEvaluationInput = DecideEvaluationParams & DecideEvaluationRequestInput;

export type DecideEvaluationOutput = {};
