/**
 * Monitors DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Monitors Domain Module - Composition root
 *
 * DDD: Composition root for monitors domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  MonitorRepositoryAdapter,
} from "@aetherlab/adapters/monitors";
import { getIdGeneratorService } from "@aetherlab/adapters";
import type { AdapterDynamoDBClient } from "@aetherlab/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeMonitor,
  ExecuteCreateMonitor,
  ExecuteGetMonitor,
  ExecuteListMonitors,
} from "@aetherlab/services/monitors/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  MonitorRepository,
} from "@aetherlab/services/monitors/ports";

export interface MonitorsDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    monitors: MonitorRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeMonitor;
    };
    monitors: {
      create: ExecuteCreateMonitor;
      get: ExecuteGetMonitor;
      list: ExecuteListMonitors;
    };
  };
}

export function buildMonitorsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): MonitorsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      monitors?: MonitorRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.monitors = new MonitorRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      monitors: obj.monitors!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeMonitor(executionContext, idGenerator, repos.acknowledges),
    },
    monitors: {
      create: new ExecuteCreateMonitor(executionContext, idGenerator, repos.monitors),
      get: new ExecuteGetMonitor(executionContext, idGenerator, repos.monitors),
      list: new ExecuteListMonitors(executionContext, idGenerator, repos.monitors),
    },
  };
  return { repos, useCases: useCases as MonitorsDomainModule["useCases"] };
}
