/**
 * Deployments DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Deployments Domain Module - Composition root
 *
 * DDD: Composition root for deployments domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DecisionRepositoryAdapter,
  DeployRepositoryAdapter,
  DeploymentRepositoryAdapter,
  RetireRepositoryAdapter,
  RollbackRepositoryAdapter,
} from "@aetherlab/adapters/deployments";
import { getIdGeneratorService } from "@aetherlab/adapters";
import type { AdapterDynamoDBClient } from "@aetherlab/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDecideDeployment,
  ExecuteExecuteDeployment,
  ExecuteGetDeployment,
  ExecuteListDeployments,
  ExecuteRequestDeployment,
  ExecuteRetireDeployment,
  ExecuteRollbackDeployment,
} from "@aetherlab/services/deployments/usecases";
// Ports (interfaces)
import type {
  DecisionRepository,
  DeployRepository,
  DeploymentRepository,
  RetireRepository,
  RollbackRepository,
} from "@aetherlab/services/deployments/ports";

export interface DeploymentsDomainModule {
  repos: {
    decisions: DecisionRepository;
    deployments: DeploymentRepository;
    deploys: DeployRepository;
    retires: RetireRepository;
    rollbacks: RollbackRepository;
  };
  useCases: {
    decisions: {
      get: ExecuteDecideDeployment;
    };
    deployments: {
      create: ExecuteRequestDeployment;
      get: ExecuteGetDeployment;
      list: ExecuteListDeployments;
    };
    deploys: {
      create: ExecuteExecuteDeployment;
    };
    retires: {
      get: ExecuteRetireDeployment;
    };
    rollbacks: {
      get: ExecuteRollbackDeployment;
    };
  };
}

export function buildDeploymentsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DeploymentsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      decisions?: DecisionRepository;
      deployments?: DeploymentRepository;
      deploys?: DeployRepository;
      retires?: RetireRepository;
      rollbacks?: RollbackRepository;
    } = {};

    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    obj.deployments = new DeploymentRepositoryAdapter(dynamoClient);
    obj.deploys = new DeployRepositoryAdapter(dynamoClient);
    obj.retires = new RetireRepositoryAdapter(dynamoClient);
    obj.rollbacks = new RollbackRepositoryAdapter(dynamoClient);
    return {
      decisions: obj.decisions!,
      deployments: obj.deployments!,
      deploys: obj.deploys!,
      retires: obj.retires!,
      rollbacks: obj.rollbacks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    decisions: {
      get: new ExecuteDecideDeployment(executionContext, idGenerator, repos.decisions),
    },
    deployments: {
      create: new ExecuteRequestDeployment(executionContext, idGenerator, repos.deployments),
      get: new ExecuteGetDeployment(executionContext, idGenerator, repos.deployments),
      list: new ExecuteListDeployments(executionContext, idGenerator, repos.deployments),
    },
    deploys: {
      create: new ExecuteExecuteDeployment(executionContext, idGenerator, repos.deploys),
    },
    retires: {
      get: new ExecuteRetireDeployment(executionContext, idGenerator, repos.retires),
    },
    rollbacks: {
      get: new ExecuteRollbackDeployment(executionContext, idGenerator, repos.rollbacks),
    },
  };
  return { repos, useCases: useCases as DeploymentsDomainModule["useCases"] };
}
