/**
 * Repository interface for Project
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ProjectEntity
} from "../models/project.entity.js";
import type {
  ListProjectsParams,
  Project
} from "../types/index.js";
/**
 * ProjectRepository Interface
 */
export interface ProjectRepository extends CreateReadRepository<ProjectEntity, Project, string, ListProjectsParams> {

}
