/**
 * Evidencepacks DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evidencepacks
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Evidencepacks Domain Module - Composition root
 *
 * DDD: Composition root for evidencepacks domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  EvidencePackRepositoryAdapter,
  ExportRepositoryAdapter,
} from "@aetherlab/adapters/evidencepacks";
import { getIdGeneratorService } from "@aetherlab/adapters";
import type { AdapterDynamoDBClient } from "@aetherlab/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateModelEvidencePack,
  ExecuteExportEvidencePack,
  ExecuteGetEvidencePack,
  ExecuteListEvidencePacks,
} from "@aetherlab/services/evidencepacks/usecases";
// Ports (interfaces)
import type {
  EvidencePackRepository,
  ExportRepository,
} from "@aetherlab/services/evidencepacks/ports";

export interface EvidencepacksDomainModule {
  repos: {
    evidencePacks: EvidencePackRepository;
    exports: ExportRepository;
  };
  useCases: {
    evidencePacks: {
      create: ExecuteCreateModelEvidencePack;
      get: ExecuteGetEvidencePack;
      list: ExecuteListEvidencePacks;
    };
    exports: {
      list: ExecuteExportEvidencePack;
    };
  };
}

export function buildEvidencepacksDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): EvidencepacksDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      evidencePacks?: EvidencePackRepository;
      exports?: ExportRepository;
    } = {};

    obj.evidencePacks = new EvidencePackRepositoryAdapter(dynamoClient);
    obj.exports = new ExportRepositoryAdapter(dynamoClient);
    return {
      evidencePacks: obj.evidencePacks!,
      exports: obj.exports!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    evidencePacks: {
      create: new ExecuteCreateModelEvidencePack(executionContext, idGenerator, repos.evidencePacks),
      get: new ExecuteGetEvidencePack(executionContext, idGenerator, repos.evidencePacks),
      list: new ExecuteListEvidencePacks(executionContext, idGenerator, repos.evidencePacks),
    },
    exports: {
      list: new ExecuteExportEvidencePack(executionContext, idGenerator, repos.exports),
    },
  };
  return { repos, useCases: useCases as EvidencepacksDomainModule["useCases"] };
}
