/**
 * GetDeployment handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDeployment } from "@aetherlab/api-server/domains/deployments/handlers";
import type { DeploymentsDDDDependencies } from "@aetherlab/api-server/domains/deployments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@aetherlab/tests/shared";
import { DEPLOYMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDeployment", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DeploymentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DeploymentsDDDDependencies>(
      DEPLOYMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDeployment, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { deploymentId: entity.id };

    await getDeployment(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDeployment.execute).toHaveBeenCalledWith(expect.objectContaining({ deploymentId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { deploymentId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDeployment, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDeployment(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
