/**
 * Monitor Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: monitors
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MonitorEntity } from "@aetherlab/core/monitors/models/index.js";
import { monitorsSchemas } from "@aetherlab/core/monitors";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mon";

export function createMonitor(overrides: Partial<MonitorEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    metric: overrides.metric ?? "drift",
    modelId: overrides.modelId ?? faker.string.uuid(),
    monitorId: overrides.monitorId ?? `mon_${ulid().toLowerCase()}`,
    status: overrides.status ?? "healthy",
    threshold: overrides.threshold ?? faker.number.int(),
    ...overrides,
  };

  return monitorsSchemas.Monitor.parse(raw);
}

export function monitorBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMonitor(overrides));
}
