/**
 * ExecuteRequestDeployment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRequestDeployment Use Case
 *
 * DDD: Application use case for get Deployment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RequestDeploymentInput, RequestDeploymentOutput } from "../dto/deployment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { DeploymentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRequestDeployment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly deployment: DeploymentRepository
  ) {}

  async execute(input: RequestDeploymentInput): Promise<RequestDeploymentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.depId();

    // All field names extracted from OpenAPI spec: endpointName, highRiskException, modelId, monitorIds
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).modelId) {
      throw new ValidationError("modelId is required");
    }
    const modelId = (input as any).modelId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.deployment.requestDeployment({
      ...input,
      modelId,
      orgId: this.context.getOrgId(),
      correlationId,
      createdByActorId: this.context.getUserId(),
    } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${modelId}`);
    }

    return entity as RequestDeploymentOutput;
  }
}
