/**
 * ExecuteRollbackDeployment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRollbackDeployment Use Case
 *
 * DDD: Application use case for get Rollback.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RollbackDeploymentInput, RollbackDeploymentOutput } from "../dto/rollback.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { RollbackRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRollbackDeployment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rollback: RollbackRepository
  ) {}

  async execute(input: RollbackDeploymentInput): Promise<RollbackDeploymentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.depId();

    // All field names extracted from OpenAPI spec: attestation, priorDeploymentId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).deploymentId) {
      throw new ValidationError("deploymentId is required");
    }
    const deploymentId = (input as any).deploymentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.rollback.rollbackDeployment({ deploymentId: deploymentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${deploymentId}`);
    }

    return entity as RollbackDeploymentOutput;
  }
}
