/**
 * SpendRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SpendRepository Port
 *
 * DDD: Application port for spendrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListCloudSpendInput, ListCloudSpendOutput } from "../dto/spend.dto";
export interface SpendRepository {
  listCloudSpend(input: ListCloudSpendInput): Promise<ListCloudSpendOutput>;
}

export type { ListCloudSpendInput, ListCloudSpendOutput } from "../dto/spend.dto";
