/**
 * TrainingJobRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: trainingjobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TrainingJobRepository Port
 *
 * DDD: Application port for trainingjobrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTrainingJobInput, CreateTrainingJobOutput, GetTrainingJobInput, GetTrainingJobOutput, ListTrainingJobsInput, ListTrainingJobsOutput } from "../dto/training-job.dto";
export interface TrainingJobRepository {
  listTrainingJobs(input: ListTrainingJobsInput): Promise<ListTrainingJobsOutput>;
  createTrainingJob(input: CreateTrainingJobInput): Promise<CreateTrainingJobOutput>;
  getTrainingJob(input: GetTrainingJobInput): Promise<GetTrainingJobOutput>;
}

export type { CreateTrainingJobInput, CreateTrainingJobOutput, GetTrainingJobInput, GetTrainingJobOutput, ListTrainingJobsInput, ListTrainingJobsOutput } from "../dto/training-job.dto";
