/**
 * DecisionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: evaluations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DecisionRepository Port
 *
 * DDD: Application port for decisionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DecideEvaluationInput, DecideEvaluationOutput } from "../dto/decision.dto";
export interface DecisionRepository {
  decideEvaluation(input: DecideEvaluationInput): Promise<DecideEvaluationOutput>;
}

export type { DecideEvaluationInput, DecideEvaluationOutput } from "../dto/decision.dto";
