/**
 * Routes for DarkFind
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { forceRegisterDarkFind } from "../handlers/dark-find.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function darkFindRoutes(fastify: FastifyInstance) {
  // POST /v1/models/dark-finds (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/models/dark-finds",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getModelsDependenciesForRequest();
        await forceRegisterDarkFind(request, reply, deps);
      });
    }
  );


}
