/**
 * Handlers for RiskClassGate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProjectsDomainModule } from "../dependencies/projects-ddd.dependencies.js";
import type { GetRiskClassGateMatrixInput } from "@aetherlab/services/projects";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/risk-class-gates
 * Operation: getRiskClassGateMatrix
 */
export async function getRiskClassGateMatrix(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ProjectsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {};
  const result = await deps.useCases.riskClassGates.get.execute(input);
  return reply.code(200).send(result);
}


