/**
 * Handlers for DarkFind
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ModelsDomainModule } from "../dependencies/models-ddd.dependencies.js";
import type { ForceRegisterDarkFindInput } from "@aetherlab/services/models";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/models/dark-finds
 * Operation: forceRegisterDarkFind
 */
export async function forceRegisterDarkFind(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: any = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.darkFinds.get.execute(input);
  return reply.code(201).send(result);
}


