/**
 * ExecuteDecideProjectScaleQuota - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDecideProjectScaleQuota Use Case
 *
 * DDD: Application use case for get ScaleQuotum.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DecideProjectScaleQuotaInput, DecideProjectScaleQuotaOutput } from "../dto/scale-quotum.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { ScaleQuotumRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDecideProjectScaleQuota {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly scaleQuotum: ScaleQuotumRepository
  ) {}

  async execute(input: DecideProjectScaleQuotaInput): Promise<DecideProjectScaleQuotaOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prjId();

    // All field names extracted from OpenAPI spec: decision, notes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).projectId) {
      throw new ValidationError("projectId is required");
    }
    const projectId = (input as any).projectId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.scaleQuotum.decideProjectScaleQuota({ projectId: projectId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${projectId}`);
    }

    return entity as DecideProjectScaleQuotaOutput;
  }
}
