/**
 * ExecuteCreateProject - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateProject Use Case
 *
 * DDD: Application use case for create Project.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateProjectInput, CreateProjectOutput } from "../dto/project.dto";
import type { ExecutionContextService, IdGeneratorService } from "@aetherlab/services/_shared/index.js";
import type { ProjectRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateProject {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly project: ProjectRepository
  ) {}

  async execute(input: CreateProjectInput): Promise<CreateProjectOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prjId();

    // All field names extracted from OpenAPI spec: name, owner, riskClass
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.riskClass) {
      throw new ValidationError("riskClass is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.owner) {
      throw new ValidationError("owner is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (projects domain)
    const entityId = this.idGenerator.prjId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.project.createProject({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateProjectOutput;
  }
}
