/**
 * DeployRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DeployRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DeployRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DeployRepository,
} from "@aetherlab/services/deployments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DeployRepositoryDdb } from "./deploy-repository.ddb.js";

/**
 * DeployRepositoryAdapter
 *
 * Implements DeployRepository port for infrastructure layer.
 */
export class DeployRepositoryAdapter implements DeployRepository {
  private readonly ddb: DeployRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DeployRepositoryDdb(this.dynamoClient);
  }

  async executeDeployment(input: Parameters<DeployRepository['executeDeployment']>[0]): Promise<Awaited<ReturnType<DeployRepository['executeDeployment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.executeDeployment(input);
  }
}
