/**
 * RollbackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RollbackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RollbackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RollbackRepository,
} from "@aetherlab/services/deployments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RollbackRepositoryDdb } from "./rollback-repository.ddb.js";

/**
 * RollbackRepositoryAdapter
 *
 * Implements RollbackRepository port for infrastructure layer.
 */
export class RollbackRepositoryAdapter implements RollbackRepository {
  private readonly ddb: RollbackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RollbackRepositoryDdb(this.dynamoClient);
  }

  async rollbackDeployment(input: Parameters<RollbackRepository['rollbackDeployment']>[0]): Promise<Awaited<ReturnType<RollbackRepository['rollbackDeployment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.rollbackDeployment(input);
  }
}
