/**
 * RollbackRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: deployments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RollbackRepositoryDdb
 *
 * DDD: Infrastructure adapter for Rollback repository.
 * ⚠️  Missing x-dynamodb metadata - implementation not generated.
 */

import type { RollbackRepository } from "@aetherlab/services/deployments";
import { factoryOps } from "../_shared/factory-ops.js";

export class RollbackRepositoryDdb implements RollbackRepository {
  constructor(private readonly dynamoClient: any) {}

  async rollbackDeployment(input: Parameters<RollbackRepository['rollbackDeployment']>[0]): Promise<Awaited<ReturnType<RollbackRepository['rollbackDeployment']>>>  {
    return factoryOps.rollbackDeployment(input) as any;
  }
}
